apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  selector:
    matchLabels:
      app: myfirstpod
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: myfirstpod
    spec:
      containers:
      - name: myfirstpod
        image: europe-west4-docker.pkg.dev/cloudparis1/registry/visit-flask # update to a new image
        ports:
        - containerPort: 80
