apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
  labels:
    env: test
spec:
  containers:
  - name: myfirstflask
    image: europe-west4-docker.pkg.dev/cloudparis1/registry/visit-flask
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "200m"
      limits:
        cpu: "200m"
